#!/usr/bin/env python3
"""Regenerate marketplace.json, each plugin.json, and SKILLS.md from what is on disk.

Single source of truth is the filesystem: whatever sits under
plugins/<plugin>/skills/<skill>/SKILL.md is what ships. Editable metadata
(owner, version, plugin blurbs) lives in marketplace.config.json.

Run after adding, removing, or renaming any skill:  python scripts/build_manifest.py
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CONFIG = ROOT / "marketplace.config.json"


def parse_frontmatter(path: Path) -> dict[str, str]:
    """Minimal YAML frontmatter reader. Handles quoted scalars and folded
    continuation lines, which is the full extent of what SKILL.md files use."""
    text = path.read_text(encoding="utf-8", errors="replace")
    if not text.startswith("---"):
        return {}
    end = text.find("\n---", 3)
    if end == -1:
        return {}
    block = text[text.find("\n", 3) + 1 : end]

    fields: dict[str, str] = {}
    key: str | None = None
    for line in block.splitlines():
        match = re.match(r"^([A-Za-z_][\w-]*):\s*(.*)$", line)
        if match:
            key, value = match.group(1), match.group(2)
            fields[key] = value
        elif key and line.strip():
            fields[key] = (fields[key] + " " + line.strip()).strip()

    for key, value in list(fields.items()):
        value = value.strip()
        if len(value) >= 2 and value[0] == value[-1] and value[0] in "\"'":
            value = value[1:-1]
        fields[key] = value.strip()
    return fields


def write(path: Path, text: str) -> None:
    """Always LF, on every platform: these files are committed, and a CRLF
    rewrite would show up as a whole-file diff on the next machine."""
    path.write_text(text, encoding="utf-8", newline="\n")


def collect(plugin_dir: Path) -> list[dict[str, str]]:
    skills_dir = plugin_dir / "skills"
    if not skills_dir.is_dir():
        return []
    found = []
    for entry in sorted(skills_dir.iterdir(), key=lambda p: p.name.lower()):
        manifest = entry / "SKILL.md"
        if not entry.is_dir() or not manifest.is_file():
            continue
        fields = parse_frontmatter(manifest)
        found.append(
            {
                "dir": entry.name,
                "name": fields.get("name") or entry.name,
                "description": fields.get("description", ""),
            }
        )
    return found


def main() -> int:
    config = json.loads(CONFIG.read_text(encoding="utf-8"))
    version = config["version"]
    problems: list[str] = []
    entries = []
    index_lines = [
        "# Skill index",
        "",
        "Generated by `scripts/build_manifest.py` — do not edit by hand.",
        "",
    ]
    total = 0

    for spec in config["plugins"]:
        plugin_dir = ROOT / spec["source"].lstrip("./")
        skills = collect(plugin_dir)
        total += len(skills)

        seen: dict[str, str] = {}
        for skill in skills:
            if not skill["description"]:
                problems.append(f"{spec['name']}/{skill['dir']}: SKILL.md has no description")
            if skill["name"] in seen:
                problems.append(
                    f"{spec['name']}: duplicate skill name '{skill['name']}' "
                    f"({seen[skill['name']]} and {skill['dir']})"
                )
            seen[skill["name"]] = skill["dir"]
            if skill["name"] != skill["dir"]:
                problems.append(
                    f"{spec['name']}/{skill['dir']}: frontmatter name '{skill['name']}' "
                    "does not match its directory name"
                )

        plugin_json = {
            "name": spec["name"],
            "description": f"{spec['description']} {len(skills)} skills.".strip(),
            "version": version,
            "author": config["owner"],
            "homepage": config["homepage"],
            "repository": config["repository"],
            "license": config["license"],
            "keywords": spec.get("keywords", []),
        }
        out = plugin_dir / ".claude-plugin" / "plugin.json"
        out.parent.mkdir(parents=True, exist_ok=True)
        write(out, json.dumps(plugin_json, indent=2) + "\n")

        entries.append(
            {
                "name": spec["name"],
                "source": spec["source"],
                "description": plugin_json["description"],
                "version": version,
                "author": config["owner"],
                "keywords": spec.get("keywords", []),
                "category": spec.get("category", "productivity"),
            }
        )

        index_lines += [f"## {spec['name']} ({len(skills)} skills)", ""]
        for skill in skills:
            summary = skill["description"]
            if len(summary) > 200:
                summary = summary[:197].rstrip() + "..."
            index_lines.append(f"- **{skill['name']}** — {summary}")
        index_lines.append("")

    marketplace = {
        "name": config["name"],
        "owner": config["owner"],
        "description": f"{config['description']} {total} skills across {len(entries)} plugin(s).",
        "homepage": config["homepage"],
        "repository": config["repository"],
        "metadata": {"description": config["description"], "version": version},
        "plugins": entries,
    }
    manifest_path = ROOT / ".claude-plugin" / "marketplace.json"
    manifest_path.parent.mkdir(parents=True, exist_ok=True)
    write(manifest_path, json.dumps(marketplace, indent=2) + "\n")
    write(ROOT / "SKILLS.md", "\n".join(index_lines))

    print(f"wrote {manifest_path.relative_to(ROOT)}")
    print(f"  {len(entries)} plugin(s), {total} skills, version {version}")
    if problems:
        print(f"\n{len(problems)} warning(s):", file=sys.stderr)
        for problem in problems:
            print(f"  - {problem}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
